import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "philpaolella.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            marginTop: "30px",
            marginBottom: "0px",
            marginLeft: "10px",
            marginRight: "10px",
            padding: "0px",
          }}
        >
          <h1
            style={{
              textAlign: "center",
            }}
          >
            <Link href="/">🚀 philpaolella.com</Link>
          </h1>
          <h3
            style={{
              paddingTop: "20px",
              textAlign: "center",
            }}
          >
            PORTFOLIO - AWARD WINNING
          </h3>
        </nav>
        {children}
      </body>
    </html>
  );
}
